title: Şan Güneş Duran
theme: jekyll-theme-minimal
markdown: GFM
tabs: [home](https://sanduran.github.io) | [projects](https://sanduran.github.io/projects) | [big ideas](https://sanduran.github.io/big_ideas) | [documentation](https://sanduran.github.io/documentation)
